{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pickle  \n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.metrics import accuracy_score\n",
    "\n",
    "from sklearn.ensemble import RandomForestRegressor\n",
    "from sklearn.metrics import mean_squared_error, r2_score"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-09-24 20:14:29.595 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run c:\\Users\\spenc\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n"
     ]
    }
   ],
   "source": [
    "@st.cache_resource\n",
    "def load_data():\n",
    "    pickle_file_path = r'C:\\Users\\spenc\\VictorVis\\CleanData\\solo_players_df.pkl'\n",
    "    with open(pickle_file_path, 'rb') as file:\n",
    "        return pickle.load(file)\n",
    "\n",
    "solo_players_df = load_data()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Index(['real_name', 'team', 'age', 'rating', 'dpr', 'kpr', 'kast', 'impact',\n",
      "       'adr', 'rating_is_missing', 'total_kills', 'total_deaths',\n",
      "       'rounds_played', 'kd_ratio', 'maps_played', 'kills_per_round',\n",
      "       'deaths_per_round', 'assists_per_round', 'saved_by_teammate_per_round',\n",
      "       'saved_teammates_per_round', 'damage_per_round',\n",
      "       'grenade_damage_per_round', 'headshot_percentage', 'firepower_score',\n",
      "       'firepower_kills_per_round', 'firepower_damage_per_round',\n",
      "       'firepower_kills_per_round_win', 'firepower_damage_per_round_win',\n",
      "       'firepower_rounds_with_kill', 'firepower_rounds_with_multi_kill',\n",
      "       'opening_score', 'opening_kills_per_round', 'opening_deaths_per_round',\n",
      "       'opening_attempts', 'opening_success',\n",
      "       'win_percentage_after_opening_kill', 'opening_attacks_per_round',\n",
      "       'clutching_score', 'clutch_points_per_round',\n",
      "       'clutch_1on1_win_percentage', 'clutch_time_alive_per_round',\n",
      "       'clutch_saves_per_round_loss', 'clutch_last_alive_percentage',\n",
      "       'entrying_score', 'entrying_saved_by_teammate_per_round',\n",
      "       'entrying_traded_deaths_per_round', 'entrying_traded_deaths_percentage',\n",
      "       'entrying_opening_deaths_traded_percentage',\n",
      "       'entrying_assists_per_round', 'entrying_support_rounds',\n",
      "       'trading_score', 'trading_kills_per_round', 'trading_kills_percentage',\n",
      "       'trading_assisted_kills_percentage', 'trading_damage_per_kill',\n",
      "       'trading_saved_teammate_per_round', 'sniping_score',\n",
      "       'sniping_kills_per_round', 'sniping_kills_percentage',\n",
      "       'sniping_rounds_with_kills_percentage', 'sniping_multi_kill_rounds',\n",
      "       'sniping_opening_kills_per_round', 'utility_score',\n",
      "       'utility_damage_per_round', 'utility_kills_per_100_rounds',\n",
      "       'utility_flashes_thrown_per_round', 'utility_flash_assists_per_round',\n",
      "       'utility_time_opponent_flashed_per_round'],\n",
      "      dtype='object')\n"
     ]
    }
   ],
   "source": [
    "print(solo_players_df.columns)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>real_name</th>\n",
       "      <th>kd_ratio</th>\n",
       "      <th>kpr</th>\n",
       "      <th>kills_per_round</th>\n",
       "      <th>firepower_score</th>\n",
       "      <th>firepower_rounds_with_kill</th>\n",
       "      <th>impact</th>\n",
       "      <th>firepower_kills_per_round</th>\n",
       "      <th>firepower_rounds_with_multi_kill</th>\n",
       "      <th>opening_success</th>\n",
       "      <th>kast</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>team</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>no team</th>\n",
       "      <td>Dmitriy Shvorak</td>\n",
       "      <td>0.863636</td>\n",
       "      <td>0.633333</td>\n",
       "      <td>0.633333</td>\n",
       "      <td>0.755556</td>\n",
       "      <td>0.717105</td>\n",
       "      <td>0.617647</td>\n",
       "      <td>0.545455</td>\n",
       "      <td>0.517544</td>\n",
       "      <td>0.936455</td>\n",
       "      <td>0.789916</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>no team</th>\n",
       "      <td>Euan Moore</td>\n",
       "      <td>0.772727</td>\n",
       "      <td>0.733333</td>\n",
       "      <td>0.733333</td>\n",
       "      <td>0.844444</td>\n",
       "      <td>0.769737</td>\n",
       "      <td>0.632353</td>\n",
       "      <td>0.636364</td>\n",
       "      <td>0.561404</td>\n",
       "      <td>0.772575</td>\n",
       "      <td>0.731092</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>no team</th>\n",
       "      <td>Elias Olkkonen</td>\n",
       "      <td>0.575758</td>\n",
       "      <td>0.733333</td>\n",
       "      <td>0.733333</td>\n",
       "      <td>0.855556</td>\n",
       "      <td>0.684211</td>\n",
       "      <td>0.779412</td>\n",
       "      <td>0.636364</td>\n",
       "      <td>0.640351</td>\n",
       "      <td>0.605351</td>\n",
       "      <td>0.453782</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>no team</th>\n",
       "      <td>Ethan Arnold</td>\n",
       "      <td>0.469697</td>\n",
       "      <td>0.600000</td>\n",
       "      <td>0.600000</td>\n",
       "      <td>0.811111</td>\n",
       "      <td>0.677632</td>\n",
       "      <td>0.632353</td>\n",
       "      <td>0.636364</td>\n",
       "      <td>0.614035</td>\n",
       "      <td>0.454849</td>\n",
       "      <td>0.647059</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>no team</th>\n",
       "      <td>Valentin Vasilev</td>\n",
       "      <td>0.560606</td>\n",
       "      <td>0.600000</td>\n",
       "      <td>0.600000</td>\n",
       "      <td>0.788889</td>\n",
       "      <td>0.539474</td>\n",
       "      <td>0.661765</td>\n",
       "      <td>0.515152</td>\n",
       "      <td>0.517544</td>\n",
       "      <td>0.528428</td>\n",
       "      <td>0.512605</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>no team</th>\n",
       "      <td>Sean Gares</td>\n",
       "      <td>0.136364</td>\n",
       "      <td>0.133333</td>\n",
       "      <td>0.133333</td>\n",
       "      <td>0.166667</td>\n",
       "      <td>0.144737</td>\n",
       "      <td>0.176471</td>\n",
       "      <td>0.121212</td>\n",
       "      <td>0.114035</td>\n",
       "      <td>0.140468</td>\n",
       "      <td>0.302521</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>no team</th>\n",
       "      <td>Dima Lemeshchuk</td>\n",
       "      <td>0.106061</td>\n",
       "      <td>0.133333</td>\n",
       "      <td>0.133333</td>\n",
       "      <td>0.144444</td>\n",
       "      <td>0.177632</td>\n",
       "      <td>0.147059</td>\n",
       "      <td>0.151515</td>\n",
       "      <td>0.149123</td>\n",
       "      <td>0.130435</td>\n",
       "      <td>0.386555</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>no team</th>\n",
       "      <td>Zhuo Liang</td>\n",
       "      <td>0.106061</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.085526</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.060606</td>\n",
       "      <td>0.043860</td>\n",
       "      <td>0.150502</td>\n",
       "      <td>0.537815</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>no team</th>\n",
       "      <td>Fatih Dayik</td>\n",
       "      <td>0.090909</td>\n",
       "      <td>0.033333</td>\n",
       "      <td>0.033333</td>\n",
       "      <td>0.077778</td>\n",
       "      <td>0.092105</td>\n",
       "      <td>0.132353</td>\n",
       "      <td>0.060606</td>\n",
       "      <td>0.061404</td>\n",
       "      <td>0.173913</td>\n",
       "      <td>0.319328</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>no team</th>\n",
       "      <td>Jonas Wenzelsen</td>\n",
       "      <td>0.030303</td>\n",
       "      <td>0.033333</td>\n",
       "      <td>0.033333</td>\n",
       "      <td>0.088889</td>\n",
       "      <td>0.125000</td>\n",
       "      <td>0.147059</td>\n",
       "      <td>0.090909</td>\n",
       "      <td>0.105263</td>\n",
       "      <td>0.143813</td>\n",
       "      <td>0.159664</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>383 rows × 11 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                real_name  kd_ratio       kpr  kills_per_round  \\\n",
       "team                                                             \n",
       "no team   Dmitriy Shvorak  0.863636  0.633333         0.633333   \n",
       "no team        Euan Moore  0.772727  0.733333         0.733333   \n",
       "no team    Elias Olkkonen  0.575758  0.733333         0.733333   \n",
       "no team      Ethan Arnold  0.469697  0.600000         0.600000   \n",
       "no team  Valentin Vasilev  0.560606  0.600000         0.600000   \n",
       "...                   ...       ...       ...              ...   \n",
       "no team        Sean Gares  0.136364  0.133333         0.133333   \n",
       "no team   Dima Lemeshchuk  0.106061  0.133333         0.133333   \n",
       "no team        Zhuo Liang  0.106061  0.000000         0.000000   \n",
       "no team       Fatih Dayik  0.090909  0.033333         0.033333   \n",
       "no team   Jonas Wenzelsen  0.030303  0.033333         0.033333   \n",
       "\n",
       "         firepower_score  firepower_rounds_with_kill    impact  \\\n",
       "team                                                             \n",
       "no team         0.755556                    0.717105  0.617647   \n",
       "no team         0.844444                    0.769737  0.632353   \n",
       "no team         0.855556                    0.684211  0.779412   \n",
       "no team         0.811111                    0.677632  0.632353   \n",
       "no team         0.788889                    0.539474  0.661765   \n",
       "...                  ...                         ...       ...   \n",
       "no team         0.166667                    0.144737  0.176471   \n",
       "no team         0.144444                    0.177632  0.147059   \n",
       "no team         0.000000                    0.085526  0.000000   \n",
       "no team         0.077778                    0.092105  0.132353   \n",
       "no team         0.088889                    0.125000  0.147059   \n",
       "\n",
       "         firepower_kills_per_round  firepower_rounds_with_multi_kill  \\\n",
       "team                                                                   \n",
       "no team                   0.545455                          0.517544   \n",
       "no team                   0.636364                          0.561404   \n",
       "no team                   0.636364                          0.640351   \n",
       "no team                   0.636364                          0.614035   \n",
       "no team                   0.515152                          0.517544   \n",
       "...                            ...                               ...   \n",
       "no team                   0.121212                          0.114035   \n",
       "no team                   0.151515                          0.149123   \n",
       "no team                   0.060606                          0.043860   \n",
       "no team                   0.060606                          0.061404   \n",
       "no team                   0.090909                          0.105263   \n",
       "\n",
       "         opening_success      kast  \n",
       "team                                \n",
       "no team         0.936455  0.789916  \n",
       "no team         0.772575  0.731092  \n",
       "no team         0.605351  0.453782  \n",
       "no team         0.454849  0.647059  \n",
       "no team         0.528428  0.512605  \n",
       "...                  ...       ...  \n",
       "no team         0.140468  0.302521  \n",
       "no team         0.130435  0.386555  \n",
       "no team         0.150502  0.537815  \n",
       "no team         0.173913  0.319328  \n",
       "no team         0.143813  0.159664  \n",
       "\n",
       "[383 rows x 11 columns]"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "solo_players = solo_players_df[['team', 'real_name', 'kd_ratio', 'kpr', 'kills_per_round',\n",
    "                                  'firepower_score', 'firepower_rounds_with_kill',\n",
    "                                  'impact', 'firepower_kills_per_round', 'firepower_rounds_with_multi_kill',\n",
    "                                  'opening_success', 'kast']]\n",
    "\n",
    "solo_players.set_index('team', inplace=True)\n",
    "solo_players"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "'real_name' appears to be continuous. Using RandomForestRegressor.\n"
     ]
    }
   ],
   "source": [
    "X = solo_players.drop(['real_name', 'kast'], axis=1)  # Assuming 'team_name' is in your dataset\n",
    "y = solo_players['kast']\n",
    "\n",
    "# Train the model\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n",
    "model = RandomForestRegressor(n_estimators=100, random_state=42)\n",
    "model.fit(X_train, y_train)\n",
    "\n",
    "if y.dtype == 'object' or y.nunique() < 10:  # Assuming it's categorical if less than 10 unique values\n",
    "    print(\"\\n'real_name' appears to be categorical. Using RandomForestClassifier.\")\n",
    "    # Encode categorical target\n",
    "    le = LabelEncoder()\n",
    "    y = le.fit_transform(y)\n",
    "    model = RandomForestClassifier(n_estimators=100, max_depth=10, \n",
    "                                   min_samples_split=2, min_samples_leaf=1, \n",
    "                                   random_state=42)\n",
    "else:\n",
    "    print(\"\\n'real_name' appears to be continuous. Using RandomForestRegressor.\")\n",
    "    model = RandomForestRegressor(n_estimators=100, max_depth=10, \n",
    "                                  min_samples_split=2, min_samples_leaf=1, \n",
    "                                  random_state=42)\n",
    "\n",
    "# Split the data into training and testing sets\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "DeltaGenerator(_root_container=1, _parent=DeltaGenerator())"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Streamlit app\n",
    "st.title(\"Team Performance Predictor\")\n",
    "\n",
    "# Create two columns for team inputs\n",
    "col1, col2 = st.columns(2)\n",
    "\n",
    "# Function to create input fields for a team\n",
    "def team_input(column, team_name):\n",
    "    with column:\n",
    "        st.subheader(f\"{team_name} Stats\")\n",
    "        team_data = {}\n",
    "        for feature in X.columns:\n",
    "            team_data[feature] = st.number_input(f\"{feature.replace('_', ' ').title()}\", \n",
    "                                                 min_value=0.0, \n",
    "                                                 max_value=1.0, \n",
    "                                                 value=0.5, \n",
    "                                                 key=f\"{team_name}_{feature}\")\n",
    "        return pd.DataFrame([team_data])\n",
    "\n",
    "# Get input for both teams\n",
    "team1_data = team_input(col1, \"Team 1\")\n",
    "team2_data = team_input(col2, \"Team 2\")\n",
    "\n",
    "if st.button(\"Predict Winner\"):\n",
    "    # Make predictions\n",
    "    team1_pred = model.predict(team1_data)[0]\n",
    "    team2_pred = model.predict(team2_data)[0]\n",
    "\n",
    "    # Display results\n",
    "    st.subheader(\"Prediction Results\")\n",
    "    st.write(f\"Team 1 predicted KAST: {team1_pred:.2f}\")\n",
    "    st.write(f\"Team 2 predicted KAST: {team2_pred:.2f}\")\n",
    "\n",
    "    if team1_pred > team2_pred:\n",
    "        st.success(\"Team 1 is predicted to win!\")\n",
    "    elif team2_pred > team1_pred:\n",
    "        st.success(\"Team 2 is predicted to win!\")\n",
    "    else:\n",
    "        st.info(\"It's a tie based on the predictions!\")\n",
    "\n",
    "    # Display feature importances\n",
    "    st.subheader(\"Feature Importances\")\n",
    "    importances = pd.DataFrame({\n",
    "        'feature': X.columns,\n",
    "        'importance': model.feature_importances_\n",
    "    }).sort_values('importance', ascending=False)\n",
    "    st.bar_chart(importances.set_index('feature'))\n",
    "\n",
    "st.sidebar.info(\"This app predicts the winner between two teams based on their performance metrics. Enter the stats for each team and click 'Predict Winner' to see the results.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "##RandomForest Regressor \n",
    "# Create a RandomForestRegressor model\n",
    "model = RandomForestRegressor(n_estimators=128, random_state=1)\n",
    "\n",
    "# Fit the model\n",
    "model.fit(X_train, y_train)\n",
    "\n",
    "# Make predictions\n",
    "y_pred = model.predict(X_test)\n",
    "mse = mean_squared_error(y_test, y_pred)\n",
    "r2 = r2_score(y_test, y_pred)\n",
    "\n",
    "print(f\"Mean Squared Error: {mse}\")\n",
    "print(f\"R^2 Score: {r2}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create a RandomForestRegressor model\n",
    "#model = RandomForestRegressor(n_estimators=128, random_state=1)\n",
    "\n",
    "# Fit the model\n",
    "#model.fit(X_train, y_train)\n",
    "\n",
    "# Make predictions\n",
    "#y_pred = model.predict(X_test)\n",
    "#mse = mean_squared_error(y_test, y_pred)\n",
    "#r2 = r2_score(y_test, y_pred)\n",
    "\n",
    "#print(f\"Mean Squared Error: {mse}\")\n",
    "#print(f\"R^2 Score: {r2}\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
